### ISSUE TITLE
Problem with sql

### ISSUE THREAD

**Issue by m00nLP** [trentech/ProjectInventories#12]
Hey guy
We have a Problem with your Plugin

We have two Server with Bungeecord and spong but modded ( Sky Factory 3 )

Now we Need a plugin what our Inventorie from Server 1 to Server 2 transfert

Now we have a problem with your plugin. It does not create a database and if we install the plugin on the second server, it does not take the commands anymore. What is the reason for this?

**Comment by m00nLP** [comment]
Hello we Need help

**Comment by m00nLP** [comment]
Nice Support !!!

**Comment by trentech** [comment]
OK for starters by default this plugin uses H2 data file by default. You need to enable SQL in the config and set it up with your SQL Server. If it's not creating the database then it means your configuration settings don't match your SQL server and would through errors in the console, which brings up point two, I can't fix a problem without details, error logs, the version or Sponge, version of PJI the steps you took to produce the problem. "It doesn't work" is not helpful in the slightest. And last, Giving attitude because you didn't a response immediately after posting is a dick move. I have a life outside Minecraft, A job, a wife, bills to pay, you know being an adult. These projects are not all that high on my priority list and only get worked on when I have time to spare. It's not like I get paid, this isn't Spigot. So come back with more information and I'll be happy to help when I have time.
